import {
  errorSchema,
  accountLoginSchema,
  accountSchema,
  loginParamsSchema,
  categorySchema,
  categoriesSchema,
  signupParamsSchema,
  categoryParamsSchema,
  tournamentParamsSchema,
  tournamentSchema,
  tournamentFormattedDateSchema,
  tournamentsSchema,
  tournamentsFilterDateSchema,
  sportSchema,
  sportParamsSchema,
  sportsSchema,
  updateCategoryParamsSchema,
  tournamentsSponsorSchema,
  tournamentSponsorSchema,
  tournamentSponsorParamsSchema,
  registrationsParamsSchema,
  registrationsListSchema,
  registrationSchema
} from './schemas/'

export default {
  accountLogin: accountLoginSchema,
  account: accountSchema,
  loginParams: loginParamsSchema,
  error: errorSchema,
  category: categorySchema,
  categories: categoriesSchema,
  signupParams: signupParamsSchema,
  categoryParams: categoryParamsSchema,
  categoryUpdateParamsSchema: updateCategoryParamsSchema,
  tournamentParams: tournamentParamsSchema,
  tournament: tournamentSchema,
  tournaments: tournamentsSchema,
  tournamentFormattedDate: tournamentFormattedDateSchema,
  tournamentsFilterDateSchema,
  tournamentSponsorParams: tournamentSponsorParamsSchema,
  tournamentSponsor: tournamentSponsorSchema,
  tournamentsSponsor: tournamentsSponsorSchema,
  sport: sportSchema,
  sportParams: sportParamsSchema,
  sports: sportsSchema,
  registrationsParamsSchema,
  registrationsListSchema,
  registration: registrationSchema
}
